# Generated by Django 5.2.3 on 2025-06-20 09:58

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('edoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('host', 'Host'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('admin', 'Admin'), ('regular', 'Regular User')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='properties',
            name='host',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='propertyapplication',
            name='property',
        ),
        migrations.RemoveField(
            model_name='units',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='current_property',
        ),
        migrations.RemoveField(
            model_name='propertyapplication',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='propertyapplication',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='propertyapplication',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='current_unit',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='units',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='edoapi_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='edoapi_user_set_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='edoAPI.role'),
        ),
        migrations.DeleteModel(
            name='LandlordProfile',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.DeleteModel(
            name='PropertyApplication',
        ),
        migrations.DeleteModel(
            name='TenantProfile',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
