# Generated by Django 5.2.3 on 2025-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0002_role_remove_properties_host_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
