# Generated by Django 5.2.3 on 2025-07-02 09:34

import edoAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('edoAPI', '0004_hostprofile_landlordprofile_tenantprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. Use for system access control, not business logic.', related_name='edoapi_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[edoAPI.models.validate_profile_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user. Use for system access control, not business logic.', related_name='edoapi_user_set_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='HostProfile',
        ),
        migrations.DeleteModel(
            name='LandlordProfile',
        ),
        migrations.DeleteModel(
            name='TenantProfile',
        ),
    ]
