# Generated by Django 5.2.3 on 2025-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0005_remove_landlordprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('condominium', 'Condominium'), ('loft', 'Loft'), ('other', 'Other')], max_length=50)),
                ('units', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
    ]
