# Generated by Django 5.2.3 on 2025-07-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0006_landlordproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Apartment Complex', 'Apartment Complex'), ('Condominium', 'Condominium'), ('Townhouse', 'Townhouse'), ('Loft', 'Loft'), ('Villa', 'Villa'), ('Other', 'Other')], max_length=50)),
                ('total_units', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LandlordProperties',
        ),
    ]
