# Generated by Django 5.2.3 on 2025-07-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0009_alter_landlordproperty_landlord_landlordmaintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='edoAPI.tenant'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='edoAPI.unit'),
        ),
    ]
