# Generated by Django 5.2.3 on 2025-07-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0010_alter_notice_tenant_alter_notice_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_number',
            new_name='unit_id',
        ),
    ]
