# Generated by Django 5.2.3 on 2025-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0011_rename_unit_number_unit_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
