# Generated by Django 5.2.3 on 2025-08-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0014_vacatenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='edoAPI.landlordproperty'),
        ),
        migrations.DeleteModel(
            name='VacateNotice',
        ),
    ]
