# Generated by Django 5.2.3 on 2025-09-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0016_remove_notice_is_general_remove_notice_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacateNotice',
        ),
    ]
