# Generated by Django 5.2.3 on 2025-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0017_delete_vacatenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordproperty',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Townhouse', 'Townhouse'), ('Office', 'Office'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=50),
        ),
    ]
