# Generated by Django 5.2.6 on 2025-10-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoAPI', '0019_vacaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaterequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
